# Generated by Django 4.0.3 on 2022-03-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
