# Generated by Django 4.0.3 on 2022-03-24 22:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_remove_user_age_user_email_user_password_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=32)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='this', max_length=200, null=True), size=8)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='owner',
            field=models.CharField(max_length=32),
        ),
    ]
