# Generated by Django 4.0.3 on 2022-03-25 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_home_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userphoto',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
